---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-provision-mydomain-com-v1alpha1-provisionrequest
  failurePolicy: Fail
  name: mprovisionrequest.kb.io
  rules:
  - apiGroups:
    - provision.mydomain.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - provisionrequests
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-provision-mydomain-com-v1alpha1-provisionrequest
  failurePolicy: Fail
  name: vprovisionrequest.kb.io
  rules:
  - apiGroups:
    - provision.mydomain.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - provisionrequests
  sideEffects: None
