---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
- apiGroups:
  - provision.mydomain.com
  resources:
  - provisionrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - provision.mydomain.com
  resources:
  - provisionrequests/finalizers
  verbs:
  - update
- apiGroups:
  - provision.mydomain.com
  resources:
  - provisionrequests/status
  verbs:
  - get
  - patch
  - update
